/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardLayoutImport } from './routes/_authenticated/_dashboard-layout'
import { Route as AuthenticatedCanvaLayoutImport } from './routes/_authenticated/_canva-layout'
import { Route as AuthenticatedDashboardLayoutIndexImport } from './routes/_authenticated/_dashboard-layout/index'
import { Route as AuthenticatedCanvaLayoutNumberFieldImport } from './routes/_authenticated/_canva-layout/number-field'
import { Route as AuthenticatedCanvaLayoutMenuImport } from './routes/_authenticated/_canva-layout/menu'
import { Route as AuthenticatedCanvaLayoutFieldsetImport } from './routes/_authenticated/_canva-layout/fieldset'
import { Route as AuthenticatedCanvaLayoutFieldImport } from './routes/_authenticated/_canva-layout/field'
import { Route as AuthenticatedCanvaLayoutDialogImport } from './routes/_authenticated/_canva-layout/dialog'
import { Route as AuthenticatedCanvaLayoutAvatarImport } from './routes/_authenticated/_canva-layout/avatar'
import { Route as AuthenticatedCanvaLayoutAccordionImport } from './routes/_authenticated/_canva-layout/accordion'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCanvaLayoutRoute = AuthenticatedCanvaLayoutImport.update({
  id: '/_canva-layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutNumberFieldRoute =
  AuthenticatedCanvaLayoutNumberFieldImport.update({
    id: '/number-field',
    path: '/number-field',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutMenuRoute =
  AuthenticatedCanvaLayoutMenuImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutFieldsetRoute =
  AuthenticatedCanvaLayoutFieldsetImport.update({
    id: '/fieldset',
    path: '/fieldset',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutFieldRoute =
  AuthenticatedCanvaLayoutFieldImport.update({
    id: '/field',
    path: '/field',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutDialogRoute =
  AuthenticatedCanvaLayoutDialogImport.update({
    id: '/dialog',
    path: '/dialog',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutAvatarRoute =
  AuthenticatedCanvaLayoutAvatarImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

const AuthenticatedCanvaLayoutAccordionRoute =
  AuthenticatedCanvaLayoutAccordionImport.update({
    id: '/accordion',
    path: '/accordion',
    getParentRoute: () => AuthenticatedCanvaLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_canva-layout': {
      id: '/_authenticated/_canva-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedCanvaLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_dashboard-layout': {
      id: '/_authenticated/_dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_canva-layout/accordion': {
      id: '/_authenticated/_canva-layout/accordion'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutAccordionImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/avatar': {
      id: '/_authenticated/_canva-layout/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutAvatarImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/dialog': {
      id: '/_authenticated/_canva-layout/dialog'
      path: '/dialog'
      fullPath: '/dialog'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutDialogImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/field': {
      id: '/_authenticated/_canva-layout/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutFieldImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/fieldset': {
      id: '/_authenticated/_canva-layout/fieldset'
      path: '/fieldset'
      fullPath: '/fieldset'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutFieldsetImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/menu': {
      id: '/_authenticated/_canva-layout/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutMenuImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_canva-layout/number-field': {
      id: '/_authenticated/_canva-layout/number-field'
      path: '/number-field'
      fullPath: '/number-field'
      preLoaderRoute: typeof AuthenticatedCanvaLayoutNumberFieldImport
      parentRoute: typeof AuthenticatedCanvaLayoutImport
    }
    '/_authenticated/_dashboard-layout/': {
      id: '/_authenticated/_dashboard-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexImport
      parentRoute: typeof AuthenticatedDashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedCanvaLayoutRouteChildren {
  AuthenticatedCanvaLayoutAccordionRoute: typeof AuthenticatedCanvaLayoutAccordionRoute
  AuthenticatedCanvaLayoutAvatarRoute: typeof AuthenticatedCanvaLayoutAvatarRoute
  AuthenticatedCanvaLayoutDialogRoute: typeof AuthenticatedCanvaLayoutDialogRoute
  AuthenticatedCanvaLayoutFieldRoute: typeof AuthenticatedCanvaLayoutFieldRoute
  AuthenticatedCanvaLayoutFieldsetRoute: typeof AuthenticatedCanvaLayoutFieldsetRoute
  AuthenticatedCanvaLayoutMenuRoute: typeof AuthenticatedCanvaLayoutMenuRoute
  AuthenticatedCanvaLayoutNumberFieldRoute: typeof AuthenticatedCanvaLayoutNumberFieldRoute
}

const AuthenticatedCanvaLayoutRouteChildren: AuthenticatedCanvaLayoutRouteChildren =
  {
    AuthenticatedCanvaLayoutAccordionRoute:
      AuthenticatedCanvaLayoutAccordionRoute,
    AuthenticatedCanvaLayoutAvatarRoute: AuthenticatedCanvaLayoutAvatarRoute,
    AuthenticatedCanvaLayoutDialogRoute: AuthenticatedCanvaLayoutDialogRoute,
    AuthenticatedCanvaLayoutFieldRoute: AuthenticatedCanvaLayoutFieldRoute,
    AuthenticatedCanvaLayoutFieldsetRoute:
      AuthenticatedCanvaLayoutFieldsetRoute,
    AuthenticatedCanvaLayoutMenuRoute: AuthenticatedCanvaLayoutMenuRoute,
    AuthenticatedCanvaLayoutNumberFieldRoute:
      AuthenticatedCanvaLayoutNumberFieldRoute,
  }

const AuthenticatedCanvaLayoutRouteWithChildren =
  AuthenticatedCanvaLayoutRoute._addFileChildren(
    AuthenticatedCanvaLayoutRouteChildren,
  )

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCanvaLayoutRoute: typeof AuthenticatedCanvaLayoutRouteWithChildren
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCanvaLayoutRoute: AuthenticatedCanvaLayoutRouteWithChildren,
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/accordion': typeof AuthenticatedCanvaLayoutAccordionRoute
  '/avatar': typeof AuthenticatedCanvaLayoutAvatarRoute
  '/dialog': typeof AuthenticatedCanvaLayoutDialogRoute
  '/field': typeof AuthenticatedCanvaLayoutFieldRoute
  '/fieldset': typeof AuthenticatedCanvaLayoutFieldsetRoute
  '/menu': typeof AuthenticatedCanvaLayoutMenuRoute
  '/number-field': typeof AuthenticatedCanvaLayoutNumberFieldRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedCanvaLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/accordion': typeof AuthenticatedCanvaLayoutAccordionRoute
  '/avatar': typeof AuthenticatedCanvaLayoutAvatarRoute
  '/dialog': typeof AuthenticatedCanvaLayoutDialogRoute
  '/field': typeof AuthenticatedCanvaLayoutFieldRoute
  '/fieldset': typeof AuthenticatedCanvaLayoutFieldsetRoute
  '/menu': typeof AuthenticatedCanvaLayoutMenuRoute
  '/number-field': typeof AuthenticatedCanvaLayoutNumberFieldRoute
  '/': typeof AuthenticatedDashboardLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_canva-layout': typeof AuthenticatedCanvaLayoutRouteWithChildren
  '/_authenticated/_dashboard-layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/_canva-layout/accordion': typeof AuthenticatedCanvaLayoutAccordionRoute
  '/_authenticated/_canva-layout/avatar': typeof AuthenticatedCanvaLayoutAvatarRoute
  '/_authenticated/_canva-layout/dialog': typeof AuthenticatedCanvaLayoutDialogRoute
  '/_authenticated/_canva-layout/field': typeof AuthenticatedCanvaLayoutFieldRoute
  '/_authenticated/_canva-layout/fieldset': typeof AuthenticatedCanvaLayoutFieldsetRoute
  '/_authenticated/_canva-layout/menu': typeof AuthenticatedCanvaLayoutMenuRoute
  '/_authenticated/_canva-layout/number-field': typeof AuthenticatedCanvaLayoutNumberFieldRoute
  '/_authenticated/_dashboard-layout/': typeof AuthenticatedDashboardLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/auth/callback'
    | '/accordion'
    | '/avatar'
    | '/dialog'
    | '/field'
    | '/fieldset'
    | '/menu'
    | '/number-field'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/auth/callback'
    | '/accordion'
    | '/avatar'
    | '/dialog'
    | '/field'
    | '/fieldset'
    | '/menu'
    | '/number-field'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_canva-layout'
    | '/_authenticated/_dashboard-layout'
    | '/auth/callback'
    | '/_authenticated/_canva-layout/accordion'
    | '/_authenticated/_canva-layout/avatar'
    | '/_authenticated/_canva-layout/dialog'
    | '/_authenticated/_canva-layout/field'
    | '/_authenticated/_canva-layout/fieldset'
    | '/_authenticated/_canva-layout/menu'
    | '/_authenticated/_canva-layout/number-field'
    | '/_authenticated/_dashboard-layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login",
        "/auth/callback"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_canva-layout",
        "/_authenticated/_dashboard-layout"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/_canva-layout": {
      "filePath": "_authenticated/_canva-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_canva-layout/accordion",
        "/_authenticated/_canva-layout/avatar",
        "/_authenticated/_canva-layout/dialog",
        "/_authenticated/_canva-layout/field",
        "/_authenticated/_canva-layout/fieldset",
        "/_authenticated/_canva-layout/menu",
        "/_authenticated/_canva-layout/number-field"
      ]
    },
    "/_authenticated/_dashboard-layout": {
      "filePath": "_authenticated/_dashboard-layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_dashboard-layout/"
      ]
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/_authenticated/_canva-layout/accordion": {
      "filePath": "_authenticated/_canva-layout/accordion.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/avatar": {
      "filePath": "_authenticated/_canva-layout/avatar.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/dialog": {
      "filePath": "_authenticated/_canva-layout/dialog.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/field": {
      "filePath": "_authenticated/_canva-layout/field.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/fieldset": {
      "filePath": "_authenticated/_canva-layout/fieldset.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/menu": {
      "filePath": "_authenticated/_canva-layout/menu.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_canva-layout/number-field": {
      "filePath": "_authenticated/_canva-layout/number-field.tsx",
      "parent": "/_authenticated/_canva-layout"
    },
    "/_authenticated/_dashboard-layout/": {
      "filePath": "_authenticated/_dashboard-layout/index.tsx",
      "parent": "/_authenticated/_dashboard-layout"
    }
  }
}
ROUTE_MANIFEST_END */
