/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as SidebarLayoutImport } from './routes/_sidebarLayout'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated.index'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as AuthenticatedAvatarImport } from './routes/_authenticated.avatar'
import { Route as AuthenticatedAccordionImport } from './routes/_authenticated.accordion'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const SidebarLayoutRoute = SidebarLayoutImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAvatarRoute = AuthenticatedAvatarImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAccordionRoute = AuthenticatedAccordionImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_sidebarLayout': {
      id: '/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/accordion': {
      id: '/_authenticated/accordion'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AuthenticatedAccordionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/avatar': {
      id: '/_authenticated/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AuthenticatedAvatarImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedAccordionRoute: typeof AuthenticatedAccordionRoute
  AuthenticatedAvatarRoute: typeof AuthenticatedAvatarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccordionRoute: AuthenticatedAccordionRoute,
  AuthenticatedAvatarRoute: AuthenticatedAvatarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof SidebarLayoutRoute
  '/login': typeof LoginRoute
  '/accordion': typeof AuthenticatedAccordionRoute
  '/avatar': typeof AuthenticatedAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '': typeof SidebarLayoutRoute
  '/login': typeof LoginRoute
  '/accordion': typeof AuthenticatedAccordionRoute
  '/avatar': typeof AuthenticatedAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_sidebarLayout': typeof SidebarLayoutRoute
  '/login': typeof LoginRoute
  '/_authenticated/accordion': typeof AuthenticatedAccordionRoute
  '/_authenticated/avatar': typeof AuthenticatedAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/login' | '/accordion' | '/avatar' | '/auth/callback' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/login' | '/accordion' | '/avatar' | '/auth/callback' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_sidebarLayout'
    | '/login'
    | '/_authenticated/accordion'
    | '/_authenticated/avatar'
    | '/auth/callback'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SidebarLayoutRoute: typeof SidebarLayoutRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SidebarLayoutRoute: SidebarLayoutRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_sidebarLayout",
        "/login",
        "/auth/callback"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/accordion",
        "/_authenticated/avatar",
        "/_authenticated/"
      ]
    },
    "/_sidebarLayout": {
      "filePath": "_sidebarLayout.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/accordion": {
      "filePath": "_authenticated.accordion.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/avatar": {
      "filePath": "_authenticated.avatar.tsx",
      "parent": "/_authenticated"
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated.index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
